//using Events.Api.Cases.Voter;
//using Events.Domain.Factories.Voter;
//using Events.Repository.Voter;
//using Microsoft.VisualStudio.TestTools.UnitTesting;
//using Moq;

//namespace Events.AutoGeneratedTests.Voter
//{
//    [TestClass]
//    public class VoterCasesTests
//    {
//        private MockRepository mockRepository;

//        private Mock<IVoterRepository> mockVoterRepository;
//        private Mock<IVoterFactory> mockVoterFactory;

//        [TestInitialize]
//        public void TestInitialize()
//        {
//            this.mockRepository = new MockRepository(MockBehavior.Strict);

//            this.mockVoterRepository = this.mockRepository.Create<IVoterRepository>();
//            this.mockVoterFactory = this.mockRepository.Create<IVoterFactory>();
//        }

//        [TestCleanup]
//        public void TestCleanup()
//        {
//            this.mockRepository.VerifyAll();
//        }

//        [TestMethod]
//        public void TestMethod1()
//        {


//            VoterCases voterCases = this.CreateVoterCases();


//        }

//        private VoterCases CreateVoterCases()
//        {
//            return new VoterCases(
//                this.mockVoterRepository.Object,
//                this.mockVoterFactory.Object);
//        }
//    }
//}