//using AutoMapper;
//using Events.Api.Cases.Users;
//using Events.Domain.Factories.User;
//using Events.Repository.User;
//using Microsoft.VisualStudio.TestTools.UnitTesting;
//using Moq;

//namespace Events.AutoGeneratedTests.Users
//{
//    [TestClass]
//    public class UserCasesTests
//    {
//        private MockRepository mockRepository;

//        private Mock<IUserFactory> mockUserFactory;
//        private Mock<IUserRepository> mockUserRepository;
//        private Mock<IMapper> mockMapper;

//        [TestInitialize]
//        public void TestInitialize()
//        {
//            this.mockRepository = new MockRepository(MockBehavior.Strict);

//            this.mockUserFactory = this.mockRepository.Create<IUserFactory>();
//            this.mockUserRepository = this.mockRepository.Create<IUserRepository>();
//            this.mockMapper = this.mockRepository.Create<IMapper>();
//        }

//        [TestCleanup]
//        public void TestCleanup()
//        {
//            this.mockRepository.VerifyAll();
//        }

//        [TestMethod]
//        public void TestMethod1()
//        {


//            UserCases userCases = this.CreateUserCases();


//        }

//        private UserCases CreateUserCases()
//        {
//            return new UserCases(
//                this.mockUserFactory.Object,
//                this.mockUserRepository.Object,
//                this.mockMapper.Object);
//        }
//    }
//}